# Generated by Django 3.1.2 on 2020-11-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTitle', models.CharField(max_length=200)),
                ('previewTitle', models.CharField(max_length=200)),
                ('previewInfo', models.CharField(max_length=700)),
                ('moreInfo', models.CharField(max_length=700)),
                ('moreInfo2', models.CharField(max_length=700)),
                ('expertise', models.CharField(max_length=700)),
                ('profileImage', models.ImageField(null=True, upload_to='')),
                ('socialImage', models.ImageField(null=True, upload_to='')),
                ('resume', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('img_project', models.FileField(upload_to='')),
                ('homePage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='imageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgproj', models.FileField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
